### ISSUE TITLE
Articulate values & definitions for rwObserveValueForKeyPath AVMetadata

### ISSUE THREAD

**Issue by seeReadCode** [roundware/roundware-ios-framework-v2#11]
This should be written out somewhere.  See the `rwObserveValueForKeyPath` in https://github.com/seeRead/roundware-ios-digita11y/blob/master/Digita11y/TagsViewController.swift for current usage.

**Comment by hburgund** [comment]
Closing due to progress made towards client-side mixing which will make this unnecessary.
