### ISSUE TITLE
Building Framework and Example?

### ISSUE THREAD

**Issue by timcowlishaw** [roundware/roundware-ios-framework-v2#59]
Hi there folks!

I'm just starting a site-specific sound art project (with @msp, who might have also got in touch with you by other channels), and we are very excited to have discovered roundware, which seems to do almost exactly the thing we thought we were gonna have to build ourselves! 

However, I'm having some trouble trying to work out how to get the master branch of this repo building, and would really appreciate a steer if you wouldn't mind - the main problems i've come across are:

- The RWMediaFileUploader class is referenced by the project but doesn't appear to exist (I attempted to just remove the reference from the project and build anyway)
- I don't quite understand how the dependencies in the .podspec are installed - I've tried creating a new podfile which also lists them, but, while the dependencies are found, that seems to have lead to an entire cascade of other compiler errors? (I've attached a screenshot to give you an idea, but i suspect these are the result of my having done something wrong, so maybe don't focus too much on the details)

If we can use Roundware for our project that potentially frees up a fair bit of time that we could put into contributing back to the project if that'd be something useful, so if you wouldn't mind giving us a few pointers to get started, I hope we can make it worth your while!

Thanks!

Tim
![imagen](https://user-images.githubusercontent.com/4279/145714569-834dd2fc-388e-4981-b060-1e3a6bf06952.png)

**Comment by hburgund** [comment]
Hi Tim...great that you think Roundware could be useful for your project. 
Sadly, you have caught is in a bit of disorganization...apologies! The Example App included in the RW framework hasn't been updated in a very long time; we have been using an external more fully fleshed out app instead, but that's still a private repo.

Let me give you access to grab that code and though it may still require some assistance, it will certainly be closer to something usable for you to test and assess.

I will respond to your email shortly as well.

**Comment by timcowlishaw** [comment]
Hi there Halsey!

aha, thanks so much for this, and for getting back to us so quickly! The v3 app builds without issue and i'm planning to get stuck in on understanding what it's doing more today. Thanks so much for your assistance!

Tim
